# Generated by Django 5.2 on 2025-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_usuario_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='followers',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
