# Generated by Django 5.2 on 2025-06-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_usuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='complet_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
